### ISSUE TITLE
Geometry.distance `scipy.stats.mode(keepdims)`

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#701]
```
self = <sisl._core.tests.test_geometry.TestGeometry object at 0x7f82c8498d90>
setup = <sisl._core.tests.test_geometry.setup.<locals>.t object at 0x7f82c60eabc0>

    def test_distance8(self, setup):
        geom = Geometry([0] * 3, Atom(1, R=1.0), lattice=1)
        geom.set_nsc([77, 1, 1])
        d = geom.distance(0, method="min")
        assert len(d) == 1
        d = geom.distance(0, method="median")
        assert len(d) == 1
>       d = geom.distance(0, method="mode")

../../.local/lib/python3.10/site-packages/sisl/_core/tests/test_geometry.py:1254: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../.local/lib/python3.10/site-packages/sisl/_core/geometry.py:3406: in distance
    shells[i] = func(lst)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

lst = [1.0, 1.0]

    def func(lst):
>       return mode(lst, keepdims=False)[0]
E       TypeError: mode() got an unexpected keyword argument 'keepdims'

../../.local/lib/python3.10/site-packages/sisl/_core/geometry.py:3387: TypeError
```

_Originally posted by @tfrederiksen in https://github.com/zerothi/sisl/issues/700#issuecomment-1985488385_
            
Keepdims got introduced in https://github.com/scipy/scipy/commit/92ee2aeaaa696af15099656082f68593ef93994b which entered in 1.9
